"use client";

import { useEffect, useRef } from "react";
import gsap from "gsap";
import * as THREE from "three";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";
import { toCreasedNormals } from "three/examples/jsm/utils/BufferGeometryUtils.js";
import { prefersReducedMotion } from "@/lib/motion";
import { applyPlateKeyframes, createPlateStreamState, drawPlateStreams } from "@/lib/cardPlateStreams";

// Scene two's centerpiece: a metal card, rendered with real lighting (WebGL,
// not CSS3D — CSS transforms have no lights, so they can't make metal look
// like metal). Both the raised ornament and the plate are metal: the ornament
// polished gold, the plate black. A flat rounded slab, not a model: the design lives
// in four maps generated from the card art (public/card/) —
//   color  : gold where the ornament is, near-black elsewhere (metal base color)
//   rough  : polished gold, slightly rougher black
//   normal : the ornament stands proud of the plate (bevelled edges catch light)
// Metal only reads as metal when there is something to reflect, so the scene
// gets an environment (three's RoomEnvironment, a soft-box studio) plus one
// soft light from above; the card's idle sway then slides that light across
// the relief and the reflections across the gold. Nothing here reacts to the
// pointer.

// Drives the entrance from outside (HeroPinned tweens it as part of the
// scene-one -> scene-two timeline, so it reverses with it): 0 = tucked away
// below the frame, 1 = settled in the middle of it. Read every frame, like
// ringTuning.
export const cardReveal = { v: 0 };

// Dev-only bridge to CardPlateEditor.tsx (the drag-to-shape overlay for the plate's
// ribbons — see plateManualPoints in lib/cardPlateStreams.ts): the live camera and
// card mesh it needs to project a ribbon control point onto the screen, and raycast
// a drag back onto the card's own UV space. Set once the WebGL scene is up, cleared
// on teardown (reduced-motion never sets it at all, since the scene itself is skipped).
export const plateEditorLink: {
  camera: THREE.PerspectiveCamera | null;
  card: THREE.Mesh | null;
  wrap: HTMLDivElement | null;
} = { camera: null, card: null, wrap: null };

// The two springs that chase `cardReveal.v` (see the render loop). Module-level
// so the entrance can be replayed from outside.
const rise = { x: 0, v: 0 };
const spin = { x: 0, v: 0 };
// The idle sway's weight (0..1, a critically damped spring so it starts and
// ends with zero slope) and its own clock. The clock only advances by `w` per
// second, and every sway term is a plain sine, so at the moment the sway starts
// every term is 0 with zero speed: the hand-off from the entrance is seamless.
const idle = { w: 0, v: 0, t: 0 };

// Dev helper (CardTuner's "replay" button): put the card back below the frame
// with the springs at rest, then bring it in again over the same 0.8s the scene
// transition uses.
export function replayCardEntrance() {
  rise.x = rise.v = spin.x = spin.v = idle.w = idle.v = idle.t = 0;
  cardReveal.v = 0;
  gsap.to(cardReveal, { v: 1, ease: "none", duration: 0.8 });
}

// Live values the render loop reads every frame, seeded with the defaults
// below. CardTuner (the dev-only sliders) writes here so a look can be found
// by eye and copied back into these numbers.
export const cardTuning = {
  exposure: 1.05,
  envIntensity: 1,
  light: 1.2, // intensity of the soft light from above
  normal: 1, // strength of the ornament's relief
  roughness: 1, // multiplies the roughness map
  clearcoat: 0.25,
  idle: 1, // multiplies the idle sway once the entrance has finished
  size: 0.76,
  stiffness: 40, // spring pulling the entrance toward its target (higher = snappier)
  damping: 0.6, // damping ratio: 1 = no overshoot, lower = bouncier settle
  turns: 1, // full turns about its vertical axis on the way up; it lands face-on
  tint: "#ffffff", // multiplies the color map
  lightColor: "#fff4e0",
  // The front's plate (everything color.png's gold-detection called "not gold") is
  // replaced at render time by a set of flowing ribbons — parallel colored streaks
  // over color.png's own near-black plate — instead of a flat color. They're drawn as
  // real flow-field streamlines on a 2D canvas (lib/cardPlateStreams.ts), not
  // approximated with a GLSL formula: see that file's header for why. The gold
  // ornament itself is untouched: color.png is still the single source of truth for
  // it, and mask.png (already generated by gen-card-maps.py, previously unused) is
  // what tells the shader where the plate is.
  plateMix: 1, // 0 = color.png's own plate (unchanged look), 1 = fully the ribbons
  plateCount: 6, // how many streamlines
  plateNoiseScale: 1.6, // spatial frequency of the flow field: lower = broader, slower bends
  plateSway: 0.9, // how strongly the field deflects a streamline off a straight line
  plateForwardBias: 0.85, // how strongly each streamline is pushed to keep advancing (vs. free to loop)
  plateWidthPx: 26, // stroke width, in canvas px (canvas resolution: see CardScene's makeFace)
  plateSpeed: 0.06, // flow speed
  // A Unity-Animation-window-style scrub: 1 freezes the flow at plateTimeScrub (in
  // the same seconds-elapsed units the normal auto-advancing clock uses) instead of
  // advancing it every frame, so plateTimeScrub can be dragged — or, once its input
  // is focused, stepped one frame at a time with the arrow keys — to inspect or land
  // on one exact moment of the pattern. 0 = normal playback.
  plateTimeHold: 0,
  plateTimeScrub: 0,
  plateBrightness: 1,
  // A fine halftone dot grid over the whole plate (background and ribbons alike,
  // never the gold) — the printed-card texture reference art has instead of a flat
  // fill. plateDotScale is cells per UV unit (higher = smaller/denser dots),
  // plateDotSize the dot's radius within its cell (0..~0.45), plateDotDarken how much
  // it darkens at the dot centers (0 = invisible).
  plateDotScale: 90,
  plateDotSize: 0.12,
  plateDotDarken: 0.14,
  // Gradient the ribbons sweep through (canvas x, which is the final upright card's
  // vertical axis — see CARD_ROLL), not blended across area, so neighbouring hues stay
  // clean instead of averaging into mud.
  plateColorA: "#e8b23d",
  plateColorB: "#e0552b",
  plateColorC: "#c81f6e",
  plateColorD: "#7a2f8f",
};

// The canvas the plate's streamlines are drawn onto (see lib/cardPlateStreams.ts),
// sized in the card art's own texture space — same aspect as color.png/mask.png, not
// the screen. Kept modest: it's redrawn every frame the card is visible.
const PLATE_CANVAS_W = 700;
const PLATE_CANVAS_H = Math.round(PLATE_CANVAS_W / (1576 / 923));

// Exported for CardPlateEditor.tsx, which needs the same front-face local geometry
// (uv -> local xyz) to project a ribbon control point onto the screen.
export const CARD_W = 1576 / 923; // aspect of the art (1576 x 923); height is 1
export const CARD_H = 1;
// The art is landscape; the card stands upright, so it is rolled a quarter turn
// (counter-clockwise: the two logos along the top, the striped ornament at the
// bottom). Flip the sign to turn it the other way up.
const CARD_ROLL = Math.PI / 2;
export const CARD_D = 0.03;
// Corner radius, in card heights (a bank card is ~0.055). Keep it under ~0.06
// or it starts to clip the art's own chamfered frame corners.
const CORNER_RADIUS = 0.02;
// Fractions of the canvas the card may fill before the idle sway would clip it.
const FILL_W = 0.74;
const FILL_H = 0.72;
const FOV = 30;
// Idle sway (radians / world units at idle = 1): a slow yaw and pitch that let
// the light travel across the relief, a hint of roll, and a gentle float.
const IDLE_YAW = 0.2;
const IDLE_PITCH = 0.07;
const IDLE_ROLL = 0.02;
const IDLE_FLOAT = 0.035;

// A rounded-rectangle slab, extruded to the card's thickness. The art's UVs
// are rewritten from the shape's own coordinates so the front face maps the
// four textures 1:1 whatever the corner radius (ExtrudeGeometry's stock UVs are
// in world units). The rim is smooth-shaded around the corners, but the edge
// between face and rim stays a hard 90 degrees, like the flat card in the art.
function createCardGeometry() {
  const hw = CARD_W / 2;
  const hh = CARD_H / 2;
  const r = CORNER_RADIUS;
  const shape = new THREE.Shape();
  shape.moveTo(-hw + r, -hh);
  shape.lineTo(hw - r, -hh);
  shape.absarc(hw - r, -hh + r, r, -Math.PI / 2, 0, false);
  shape.lineTo(hw, hh - r);
  shape.absarc(hw - r, hh - r, r, 0, Math.PI / 2, false);
  shape.lineTo(-hw + r, hh);
  shape.absarc(-hw + r, hh - r, r, Math.PI / 2, Math.PI, false);
  shape.lineTo(-hw, -hh + r);
  shape.absarc(-hw + r, -hh + r, r, Math.PI, Math.PI * 1.5, false);

  const extruded = new THREE.ExtrudeGeometry(shape, { depth: CARD_D, bevelEnabled: false, curveSegments: 24 });
  extruded.translate(0, 0, -CARD_D / 2);
  // Smooths the rim's normals in place (the geometry is already non-indexed).
  const geometry = toCreasedNormals(extruded, THREE.MathUtils.degToRad(60));

  const pos = geometry.attributes.position;
  const uv = geometry.attributes.uv;
  for (let i = 0; i < pos.count; i++) {
    uv.setXY(i, pos.getX(i) / CARD_W + 0.5, pos.getY(i) / CARD_H + 0.5);
  }
  // The back cap shows its own art (public/card/back/). Seen from behind, after the
  // card has turned about its vertical axis, the same UVs would read mirrored
  // along the art's vertical, so flip v there to make the back read correctly.
  const lids = geometry.groups[0];
  const backStart = lids.start;
  const backEnd = lids.start + lids.count / 2;
  for (let i = backStart; i < backEnd; i++) {
    uv.setY(i, 1 - uv.getY(i));
  }
  uv.needsUpdate = true;

  // Extrude emits the lids (back cap first, then front cap) as group 0 and the
  // rim as group 1; split them so front, back and rim can each have a material.
  const rim = geometry.groups[1];
  geometry.clearGroups();
  geometry.addGroup(rim.start, rim.count, 0);
  geometry.addGroup(lids.start + lids.count / 2, lids.count / 2, 1);
  geometry.addGroup(lids.start, lids.count / 2, 2);
  return geometry;
}

// `front` picks which front design to show: the folder public/card/front/<front>/.
// The back is always public/card/back/, one design for every front.
export default function CardScene({ front = "main" }: { front?: string }) {
  const wrapRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const wrap = wrapRef.current;
    if (!wrap) return;
    if (prefersReducedMotion()) return;

    const renderer = new THREE.WebGLRenderer({ alpha: true, antialias: true, powerPreference: "high-performance" });
    renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    renderer.toneMappingExposure = cardTuning.exposure;
    wrap.appendChild(renderer.domElement);

    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(FOV, 1, 0.1, 50);

    const pmrem = new THREE.PMREMGenerator(renderer);
    const roomEnv = new RoomEnvironment();
    const envMap = pmrem.fromScene(roomEnv, 0.04).texture;
    scene.environment = envMap;
    scene.environmentIntensity = cardTuning.envIntensity;
    roomEnv.dispose();

    // One soft light from above, slightly in front: it skims the raised
    // ornament's upper edges (the relief) and leaves the flat faces evenly lit,
    // on top of the environment's reflections. Fixed; the card moves under it.
    const light = new THREE.DirectionalLight(cardTuning.lightColor, cardTuning.light);
    light.position.set(0, 3, 1.5);
    scene.add(light);

    const loader = new THREE.TextureLoader();
    const maxAniso = renderer.capabilities.getMaxAnisotropy();
    const load = (path: string, srgb: boolean) => {
      const t = loader.load(`/card/${path}.png`);
      t.anisotropy = maxAniso;
      if (srgb) t.colorSpace = THREE.SRGBColorSpace;
      return t;
    };
    // Front and back are separate sets of the same three maps: <dir>/color, /rough,
    // /normal (see docs/card-assets.md).
    const textures: THREE.Texture[] = [];
    // `animatePlate` swaps the plate (everything mask.png marks as not-gold) for the
    // slow flowing color read from cardTuning.plate* every frame, instead of the flat
    // near-black baked into color.png. Only the front uses it for now — see the
    // cardTuning.plate* comment above.
    const makeFace = (dir: string, animatePlate: boolean) => {
      const map = load(`${dir}/color`, true);
      const roughnessMap = load(`${dir}/rough`, false);
      const normalMap = load(`${dir}/normal`, false);
      textures.push(map, roughnessMap, normalMap);
      const material = new THREE.MeshPhysicalMaterial({
        map,
        metalness: 1,
        roughness: 1,
        roughnessMap,
        normalMap,
        normalScale: new THREE.Vector2(cardTuning.normal, cardTuning.normal),
        clearcoat: cardTuning.clearcoat,
        clearcoatRoughness: 0.25,
      });

      let plateCanvas:
        | {
            canvas: HTMLCanvasElement;
            ctx: CanvasRenderingContext2D;
            texture: THREE.CanvasTexture;
            streamState: ReturnType<typeof createPlateStreamState>;
          }
        | undefined;
      if (animatePlate) {
        const maskMap = load(`${dir}/mask`, false);
        textures.push(maskMap);

        const canvas = document.createElement("canvas");
        canvas.width = PLATE_CANVAS_W;
        canvas.height = PLATE_CANVAS_H;
        const ctx = canvas.getContext("2d");
        if (!ctx) throw new Error("2D canvas context unavailable for the card's plate streamlines");
        const streamTex = new THREE.CanvasTexture(canvas);
        streamTex.colorSpace = THREE.SRGBColorSpace;
        plateCanvas = { canvas, ctx, texture: streamTex, streamState: createPlateStreamState() };

        const plateUniforms = {
          uPlateMask: { value: maskMap },
          uPlateStreamTex: { value: streamTex },
          uPlateMix: { value: cardTuning.plateMix },
          uPlateBrightness: { value: cardTuning.plateBrightness },
          uPlateDotScale: { value: cardTuning.plateDotScale },
          uPlateDotSize: { value: cardTuning.plateDotSize },
          uPlateDotDarken: { value: cardTuning.plateDotDarken },
        };
        material.userData.plateUniforms = plateUniforms;
        material.onBeforeCompile = (shader) => {
          Object.assign(shader.uniforms, plateUniforms);
          shader.fragmentShader = shader.fragmentShader
            .replace(
              "#include <map_pars_fragment>",
              `#include <map_pars_fragment>
              uniform sampler2D uPlateMask;
              uniform sampler2D uPlateStreamTex;
              uniform float uPlateMix;
              uniform float uPlateBrightness;
              uniform float uPlateDotScale;
              uniform float uPlateDotSize;
              uniform float uPlateDotDarken;
              // Distance (0 at cell center) from vMapUv to the nearest point on a regular
              // grid of uPlateDotScale cells per UV unit — the halftone dot texture below
              // reads it as "how deep into a dot" a pixel is.
              float plateDotField(vec2 uv, float scale) {
                vec2 cell = fract(uv * scale) - 0.5;
                return length(cell);
              }`,
            )
            .replace(
              "#include <map_fragment>",
              `#ifdef USE_MAP
                vec4 sampledDiffuseColor = texture2D( map, vMapUv );
                #ifdef DECODE_VIDEO_TEXTURE
                  sampledDiffuseColor = sRGBTransferEOTF( sampledDiffuseColor );
                #endif
                // uPlateStreamTex holds the flow-field streamlines traced on a 2D canvas
                // (lib/cardPlateStreams.ts) — its alpha is the ribbon coverage, its rgb the
                // gradient color already baked in. uPlateMask (white = gold) keeps the gold
                // ornament reading straight from color.png regardless of what's under it.
                float plateMaskV = texture2D( uPlateMask, vMapUv ).r;
                vec4 streamSample = texture2D( uPlateStreamTex, vMapUv );
                vec3 plateBase = sampledDiffuseColor.rgb;
                vec3 plateWithRibbons = mix(plateBase, streamSample.rgb * uPlateBrightness, streamSample.a);
                vec3 platePixel = mix(plateBase, plateWithRibbons, uPlateMix);
                // A halftone dot grid over the whole plate — background and ribbons alike,
                // never the gold (it's darkened here, before the gold mask mix below) —
                // for the printed-card texture the reference art has instead of a flat fill.
                float plateDot = 1.0 - smoothstep(uPlateDotSize - 0.04, uPlateDotSize, plateDotField(vMapUv, uPlateDotScale));
                platePixel *= 1.0 - uPlateDotDarken * plateDot;
                vec3 facePixel = mix(platePixel, sampledDiffuseColor.rgb, plateMaskV);
                diffuseColor.rgb *= facePixel;
                diffuseColor.a *= sampledDiffuseColor.a;
              #endif`,
            );
        };
      }

      return { material, plateCanvas };
    };
    const { material: face, plateCanvas } = makeFace(`front/${front}`, true);
    const { material: backFace } = makeFace("back", false);
    const faces = [face, backFace];
    const plain = new THREE.MeshStandardMaterial({ color: 0x1e1e21, metalness: 1, roughness: 0.4 });
    const geometry = createCardGeometry();
    // Groups (see createCardGeometry): 0 = the rim, 1 = front face, 2 = back face.
    const card = new THREE.Mesh(geometry, [plain, face, backFace]);
    card.rotation.z = CARD_ROLL;
    const pivot = new THREE.Group();
    pivot.add(card);
    scene.add(pivot);
    plateEditorLink.camera = camera;
    plateEditorLink.card = card;
    plateEditorLink.wrap = wrap;

    // How far below the middle the card starts, so it begins fully out of
    // view (set by resize, in world units at the card's depth).
    let travel = 3;

    // Pull the camera back just far enough that the card fits the canvas. The
    // card stands upright, so its on-screen width is CARD_H and height CARD_W.
    const resize = () => {
      const w = wrap.clientWidth;
      const h = wrap.clientHeight;
      if (!w || !h) return;
      renderer.setSize(w, h);
      camera.aspect = w / h;
      const k = 2 * Math.tan(THREE.MathUtils.degToRad(FOV) / 2);
      const d = Math.max(CARD_H / (FILL_W * camera.aspect * k), CARD_W / (FILL_H * k));
      camera.position.set(0, 0, d);
      travel = (d * k) / 2 + CARD_W * 0.6;
      camera.updateProjectionMatrix();
    };
    const ro = new ResizeObserver(resize);
    ro.observe(wrap);
    resize();

    let raf = 0;
    let last = performance.now();
    // Only advances while the frame loop actually runs (see the early return below),
    // so the plate's flow simply pauses while the card is tucked away, not resets.
    // Overridden by cardTuning.plateTimeScrub while plateTimeHold is on — see that
    // comment.
    let plateTime = 0;
    const frame = (now: number) => {
      raf = requestAnimationFrame(frame);
      const dt = Math.min((now - last) / 1000, 1 / 20);
      last = now;
      const v = cardReveal.v;

      // The entrance is not glued to the timeline: `v` is the target, and two
      // damped springs chase it — the rise, and the spin a touch heavier so it
      // trails the rise. Underdamped, so the card overshoots its landing a
      // little and settles, instead of stopping dead where the tween ends.
      const stiffness = cardTuning.stiffness;
      const stepSpring = (s: { x: number; v: number }, damping: number) => {
        const c = 2 * damping * Math.sqrt(stiffness);
        const steps = 2; // sub-steps keep the integration stable on a slow frame
        for (let i = 0; i < steps; i++) {
          s.v += ((v - s.x) * stiffness - s.v * c) * (dt / steps);
          s.x += s.v * (dt / steps);
        }
      };
      stepSpring(rise, cardTuning.damping);
      stepSpring(spin, Math.min(cardTuning.damping + 0.15, 1.5));

      // Nothing to draw while the card is tucked away (target at rest and both
      // springs settled at it): don't spend the GPU.
      const moving = Math.max(Math.abs(rise.x - v), Math.abs(rise.v), Math.abs(spin.x - v), Math.abs(spin.v));
      if (v < 0.001 && moving < 0.001) return;

      renderer.toneMappingExposure = cardTuning.exposure;
      scene.environmentIntensity = cardTuning.envIntensity;
      light.intensity = cardTuning.light;
      light.color.set(cardTuning.lightColor);
      plateTime = cardTuning.plateTimeHold ? cardTuning.plateTimeScrub : plateTime + dt;
      for (const f of faces) {
        f.normalScale.setScalar(cardTuning.normal);
        f.roughness = cardTuning.roughness;
        f.clearcoat = cardTuning.clearcoat;
        f.color.set(cardTuning.tint);
        const plate = f.userData.plateUniforms as
          | {
              uPlateMix: { value: number };
              uPlateBrightness: { value: number };
              uPlateDotScale: { value: number };
              uPlateDotSize: { value: number };
              uPlateDotDarken: { value: number };
            }
          | undefined;
        if (plate) {
          plate.uPlateMix.value = cardTuning.plateMix;
          // Dimming (brightness < 1) is already baked into the canvas via globalAlpha
          // (see drawPlateStreams), so this only needs to handle brightening it further.
          plate.uPlateBrightness.value = Math.max(cardTuning.plateBrightness, 1);
          plate.uPlateDotScale.value = cardTuning.plateDotScale;
          plate.uPlateDotSize.value = cardTuning.plateDotSize;
          plate.uPlateDotDarken.value = cardTuning.plateDotDarken;
        }
      }
      if (plateCanvas) {
        applyPlateKeyframes(plateTime);
        drawPlateStreams(plateCanvas.ctx, PLATE_CANVAS_W, PLATE_CANVAS_H, {
          count: Math.round(cardTuning.plateCount),
          noiseScale: cardTuning.plateNoiseScale,
          sway: cardTuning.plateSway,
          forwardBias: cardTuning.plateForwardBias,
          width: cardTuning.plateWidthPx,
          timeOffset: plateTime * cardTuning.plateSpeed,
          brightness: cardTuning.plateBrightness,
          colors: [cardTuning.plateColorA, cardTuning.plateColorB, cardTuning.plateColorC, cardTuning.plateColorD],
        }, plateCanvas.streamState);
        plateCanvas.texture.needsUpdate = true;
      }

      // The idle sway starts when the entrance target is reached, and is simply
      // added on top of the entrance springs: it is not gated on those springs
      // being at rest (an underdamped one keeps ringing for a while, and a gate
      // on it flickers on and off as it passes through the landing point).
      const kIdle = 8;
      idle.v += ((v > 0.99 ? 1 : 0) - idle.w) * kIdle * dt - idle.v * 2 * Math.sqrt(kIdle) * dt;
      idle.w = Math.max(0, idle.w + idle.v * dt);
      idle.t += dt * idle.w;
      const sway = idle.w * cardTuning.idle;
      const t = idle.t;
      const enterRise = 1 - rise.x;
      const enterSpin = 1 - spin.x;
      // Entrance: rises from below the frame while spinning about its vertical
      // axis, leaning forward a little; all of it goes to nothing as the springs
      // settle. Idle: the slow sway on top. Pitch (rotation.x) is kept >= 0 in both
      // terms — negative tips the face up toward the overhead light (see that
      // light's comment above) and washes the card out white, so it only ever
      // noses forward/level, never back into the light.
      pivot.rotation.y = enterSpin * cardTuning.turns * Math.PI * 2 + sway * IDLE_YAW * Math.sin(t * 0.5);
      pivot.rotation.x = enterRise * 0.35 + sway * IDLE_PITCH * (0.5 + 0.5 * Math.sin(t * 0.37));
      pivot.rotation.z = sway * IDLE_ROLL * Math.sin(t * 0.29);
      pivot.position.set(0, -enterRise * travel + sway * IDLE_FLOAT * Math.sin(t * 0.7), 0);
      pivot.scale.setScalar(cardTuning.size);

      renderer.render(scene, camera);
    };
    raf = requestAnimationFrame(frame);

    return () => {
      cancelAnimationFrame(raf);
      ro.disconnect();
      plateEditorLink.camera = null;
      plateEditorLink.card = null;
      plateEditorLink.wrap = null;
      geometry.dispose();
      faces.forEach((f) => f.dispose());
      plain.dispose();
      textures.forEach((t) => t.dispose());
      plateCanvas?.texture.dispose();
      envMap.dispose();
      pmrem.dispose();
      renderer.dispose();
      renderer.domElement.remove();
    };
  }, [front]);

  return <div className="card-scene" ref={wrapRef} aria-hidden="true" />;
}
